### ISSUE TITLE
smallボタンのサイズ修正

### ISSUE THREAD

**Issue by akiHERO** [openameba/spindle#368]
## 概要
spindleボタンのsmallサイズの高さがデザインと違う

デザインでは32pxだが、32.9pxになってしまっている
<img width="334" alt="Screen Shot 2022-03-22 at 17 28 50" src="https://user-images.githubusercontent.com/5497896/159606294-69eec8c8-38f0-4872-8d68-84a8f6745a14.png">

## リンク
以前ボタンサイズ調整した際のデザイン
[Buttonテキストサイズ拡大時の対応](https://github.com/openameba/spindle/issues/28)

**Comment by hiloki** [comment]
Safari（Desktop）でみると、32pxのままですね。
<img width="578" alt="image" src="https://user-images.githubusercontent.com/445333/159615530-011b7263-0b27-4407-b034-8d3fb9635d8e.png">

Chrome（Desktop）だとたしかに `32.9px` に膨らんでて、`line-height` を上げれば解消されるけど...元々そうだったのか、どこかのChromeのバージョンで変わったのかな

**Comment by akiHERO** [comment]
safariだと問題ないんですねなるほど
