### ISSUE TITLE
iOSでIconButtonのアイコンが表示されない

### ISSUE THREAD

**Issue by tatz-ibz** [openameba/spindle#430]
![スクリーンショット 2022-06-21 14 28 14](https://user-images.githubusercontent.com/44389443/174722861-ac1694fc-1f54-4504-b620-ec9b43aec2e0.png)

iOSでflexbox内にsvgがあると表示されないようです。
既にIconButton利用箇所は`overflow: visible;`をsvgに付与することで対処していました。

**Comment by herablog** [comment]
@tatz-ibz 報告ありがとうございます！ちなみにわいの古シミュレータ環境だとpaddingが影響しているようでしたがそちらはちと違いそうですかね〜。

![Screen Shot 2022-06-21 at 14 52 44](https://user-images.githubusercontent.com/869023/174727881-bd3602e5-308a-4f99-8ea4-e5be9c019c21.png)

**Comment by tatz-ibz** [comment]
たしかにbuttonタグにpaddingがついてしまっているのが原因のようでした:eyes:
buttonのpaddingをリセットするようにしたらよさそうなので、ちょとこれで修正出してみようかと

![スクリーンショット_2022-06-21_15_20_56](https://user-images.githubusercontent.com/44389443/174730090-68e304de-334f-4b9e-9438-15cdb80cfe8c.png)
