### ISSUE TITLE
(spindle-ui): InlineNotificationでemphasis指定時に背景色が適用されない

### ISSUE THREAD

**Issue by sakito426** [openameba/spindle#721]
## 問題の概要

InlineNotificationコンポーネントにおいて `emphasis` を有効にした時、背景色が意図通りに適用されません。

## バージョン

0.58.6

## 具体的な問題

[InlineNotification - docs](https://ameba-spindle.web.app/?path=/docs/inlinenotification--error)を参考にemphasisを指定しても、emphasis用の背景色が適用されません。
variantが、`information`, `confirmation`, `error` いづれの場合でも同様です。

サンプルコード
```ts
<InlineNotification.Frame variant='error' emphasis visible>
  ...
</InlineNotification.Frame>
```

## キャプチャ

大変見づらいですが、文字色のみemphasis用になっており背景色がそのままになります。
![image](https://github.com/openameba/spindle/assets/4308418/2ba3e520-1eaf-4c98-9adf-fea8cae59804)

## 原因

emphasis用の背景色は [一般兄弟結合子 - ~](https://developer.mozilla.org/ja/docs/Web/CSS/General_sibling_combinator) で指定されています。
https://github.com/openameba/spindle/blob/%40openameba/spindle-ui%400.58.6/packages/spindle-ui/src/InlineNotification/InlineNotification.css#L266-L268

しかし、実際にemphasis指定時に展開されるhtmlで該当クラスは同じタグ内に存在します。
```html
<div class="spui-InlineNotification spui-InlineNotification--error spui-InlineNotification--emphasized">
  ...
</div>
```

これにより `.spui-InlineNotification--error ~ .spui-InlineNotification--emphasized` が適用されない事象が発生しています。

## 補足

[InlineNotification - docs](https://ameba-spindle.web.app/?path=/docs/inlinenotification--error)ではemphasisが正しく反映されている様に見えますが、これは、emphasis有りの直前にemphasis無しのコンポーネントが並んで表示されているためであり意図通りとは言えません。(偶然うまいこと動作している状態です)
![image](https://github.com/openameba/spindle/assets/4308418/9322a89f-6586-4cf7-98ab-40df76baefd5)
※ emphasis無しコンポーネントの`.spui-InlineNotification--error`に対する兄弟要素として、2つ目のemphasis有りコンポーネントの`.spui-InlineNotification--emphasized`が反応している。
emphasis有り無しの表示順を入れ替えるとスタイルは崩壊します。

## 解決策の提案

emphasizedの背景色指定時に一般兄弟結合子を使わないようにする

変更前
```css
.spui-InlineNotification--error ~ .spui-InlineNotification--emphasized
```

変更後
```css
.spui-InlineNotification--error.spui-InlineNotification--emphasized
```

**Comment by itsminadesu** [comment]
:ohh: 確認して修正します！ :arigatou_gozaimasu:

**Comment by sakito426** [comment]
https://github.com/openameba/spindle/issues/721#issuecomment-1562157498
わっ、やったー！ありがとうございます:pray:
ではお言葉に甘えてお願いしちゃおうかな。不明点あったらいつでも声かけてください

**Comment by yasuda-shin** [comment]
すません修正しちゃいました。
