### ISSUE TITLE
Dialogの使用例にautofocus属性の例を追加する

### ISSUE THREAD

**Issue by tokimari** [openameba/spindle#780]
[2.4.3 適切なフォーカス順序にする | Ameba Accessibility Guidelines](https://a11y-guidelines.ameba.design/2/4/3/)の元となる[WCAG 2.1の項目の解説書](https://waic.jp/translations/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html#navigation-mechanisms-focus-order-examples-head)に、事例としてダイアログのフォーカス制御について下記の記述があります。
> あるウェブページは、スクリプトでモーダルダイアログを実装している。起動ボタンを動作させると、ダイアログが開き、そのダイアログにある最初のインタラクティブな要素にフォーカスがあたる。ダイアログが開いている限り、フォーカスはダイアログ内の要素だけに限定される。ダイアログが閉じられると、フォーカスはボタン又はボタンの次にある要素へ戻る。

spindle-uiの提供するDialogにはフォーカス移動の処理は特に実装されていませんが、dialog要素を使っているので、 `autofocus` 属性を付与することで、任意の要素にフォーカスさせることができます。（多分）
例: https://codepen.io/tokimari7/pen/gOZbjXK

Dialog.BodyやDialog.ButtonGroupは子要素を利用者が自由に記述できる形式なので、Propsとして `autoFocus`などを追加するのではなく、利用時に `autofocus` 属性を子要素に付与しておくことを推奨するのはどうでしょうか。

## 実装例に autofocus 属性を追加する

```tsx
function DialogExample() {
  return (
    <Dialog.StyleOnly>
      <Dialog.Title>タイトルですよ</Dialog.Title>
      <Dialog.Body>ここに本文が入りますよ</Dialog.Body>
      <Dialog.ButtonGroup direction="column">
        <Button layout="fullWidth" size="medium" autofocus>
          Spindleをフォローする
        </Button>
        <Button layout="fullWidth" size="medium" variant="neutral">
          キャンセル
        </Button>
      </Dialog.ButtonGroup>
    </Dialog.StyleOnly>
  );
}
```

のような形式で、autofocus属性を付与した事例を追加したいです。
ちなみにautofocus属性がない場合、dialog要素内の一番初めのシーケンシャルフォーカス（Tabキーで順次フォーカスできる）可能な要素に自動でフォーカスするブラウザ**も**あります。（まちまちでした）

## Dialogの利用法に追加する

https://github.com/openameba/spindle/blob/main/packages/spindle-ui/src/Dialog/Dialog.stories.mdx#L28-L33

```
- フォーカス可能な要素に`autofocus`属性をつけると、Dialog起動時にフォーカスされます
```

みたいな感じで追加したいです。

## 関連
https://github.com/openameba/a11y-guidelines/issues/9

**Comment by herablog** [comment]
:yosagesan:

**Comment by yossydev** [comment]
@tokimari @yasuda-shin 
こちらの内容について確認させてください！！

## 実装イメージ
https://github.com/openameba/spindle/blob/main/packages/spindle-ui/src/Dialog/Dialog.stories.mdx に、以下のようなautofoucsの項目を追加するという認識であっていますでしょうか??:eyes:

```tsx
## autofocus
<Preview withSource="open">
  <Story name="DialogWithAutoFoucs">
    <DialogWithAutoFoucs />
  </Story>
</Preview>

<Source
  code={`
function DialogExample() {
  return (
    <Dialog.StyleOnly>
      <Dialog.Title>タイトルですよ</Dialog.Title>
      <Dialog.Body>ここに本文が入りますよ</Dialog.Body>
      <Dialog.ButtonGroup direction="column">
        <Button layout="fullWidth" size="medium" autofocus>
          Spindleをフォローする
        </Button>
        <Button layout="fullWidth" size="medium" variant="neutral">
          キャンセル
        </Button>
      </Dialog.ButtonGroup>
    </Dialog.StyleOnly>
  );
}
  `}
/>

<Source
  code={`
<div class="spui-Dialog">
  <p class="spui-Dialog-title">タイトルですよ</p>
  <p class="spui-Dialog-body">ここに本文が入りますよ</p>
  <div class="spui-ButtonGroup spui-ButtonGroup--column spui-ButtonGroup--medium spui-Dialog-buttonGroup">
    <button class="spui-Button spui-Button--fullWidth spui-Button--medium spui-Button--contained" type="button">Spindleをフォローする</button>
    <button class="spui-SubtleButton spui-SubtleButton--medium">とじる</button>
  </div>
</div>
  `}
/>
```

`DialogWithAutoFoucs`は`DialogExample`の中に入れます！


## 懸念点
autofoucsによって、https://ameba-spindle.web.app/?path=/docs/dialog--normal にアクセスすると、下から上にいくような動きになります！
(最初にDialogWithAutoFoucsのボタンにフォーカスが当たって、そこから一番上に移動するため)

こちらは何か対策をした方がいいでしょうか??:eyes:

**Comment by tokimari** [comment]
拾っていただきありがとうございます！

> 実装イメージ
https://github.com/openameba/spindle/blob/main/packages/spindle-ui/src/Dialog/Dialog.stories.mdx に、以下のようなautofoucsの項目を追加するという認識であっていますでしょうか?? 👀

いえ、 `autofocus` のセクションを追加するのではなく、全ての実装サンプルの一番始めのフォーカス可能な要素にautofocus属性を付与しておくイメージでいました！
たとえば、 https://github.com/openameba/spindle/blob/main/packages/spindle-ui/src/Dialog/Dialog.stories.mdx#L67 とか https://github.com/openameba/spindle/blob/main/packages/spindle-ui/src/Dialog/Dialog.stories.mdx#L94 とか https://github.com/openameba/spindle/blob/main/packages/spindle-ui/src/Dialog/Dialog.stories.mdx#L108 とかですね。

Spindle UIのDialogコンポーネント固有の機能ではなく、あくまでHTML5の dialog要素のautofocus属性を指定しているので、本来Spindle UIで特筆する内容ではないからです。
参考： [アクセシビリティの考慮 | `<dialog>`: ダイアログ要素 - HTML: ハイパーテキストマークアップ言語 | MDN](https://developer.mozilla.org/ja/docs/Web/HTML/Element/dialog#%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B7%E3%83%93%E3%83%AA%E3%83%86%E3%82%A3%E3%81%AE%E8%80%83%E6%85%AE)

ただ、なるべくautofocus属性を付与することを推奨したいこと、忘れがちなので、合わせてhttps://github.com/openameba/spindle/blob/main/packages/spindle-ui/src/Dialog/Dialog.stories.mdx#L28-L33 に追加で箇条書きの項目を加えたい、、というのがissue冒頭の `Dialogの利用法に追加する`です。

**Comment by tokimari** [comment]
懸念点ですが、いまいちわからず・・PR作成時のpreviewで動作確認してみたいです！

**Comment by yossydev** [comment]
> いえ、 `autofocus` のセクションを追加するのではなく、全ての実装サンプルの一番始めのフォーカス可能な要素にautofocus属性を付与しておくイメージでいました！ たとえば、 https://github.com/openameba/spindle/blob/main/packages/spindle-ui/src/Dialog/Dialog.stories.mdx#L67 とか https://github.com/openameba/spindle/blob/main/packages/spindle-ui/src/Dialog/Dialog.stories.mdx#L94 とか https://github.com/openameba/spindle/blob/main/packages/spindle-ui/src/Dialog/Dialog.stories.mdx#L108 とかですね。

ああ！なるほどです！！理解しました！！

> ただ、なるべくautofocus属性を付与することを推奨したいこと、忘れがちなので、合わせてhttps://github.com/openameba/spindle/blob/main/packages/spindle-ui/src/Dialog/Dialog.stories.mdx#L28-L33 に追加で箇条書きの項目を加えたい、、というのがissue冒頭の Dialogの利用法に追加するです。

:humuhumu: 
ありがとうございます！！こちらについても理解しました！！
