### ISSUE TITLE
Desing Docs: Paginationのnofollowの仕様変更

### ISSUE THREAD

**Issue by Dai7Igarashi** [openameba/spindle#826]
## 前提 / Context
[Pagination](https://github.com/openameba/spindle/tree/main/packages/spindle-ui/src/Pagination)コンポーネントに対して、ページ遷移リンクに対する`rel="nofollow"`の仕様変更があったため対応します。

## 目指すこと / Goals

- SEO要件に応じて必要なリンク設計がされる状態

## 目指さないこと / Non-goals

- `<a rel="nofollow">`以外の変更は行わない（UIなど）

## 概要 / Overview

要件によってリンク設計は異なるため、デフォルト値を用意しない。よく利用される3パターンを用意し、1つ指定してもらう。
（BREAKING CHANGE）

- 全てdofollow（全ての`<a>`に`rel="nofollow"`が付いていない状態）
- 全てnofollow（全ての`<a>`に`rel="nofollow"`が付いている状態）
- 1ページ目以外全てnofollow（1ページ目への`href`を持つ`<a>`を除く、他全ての`<a>`に`rel="nofollow"`が付いている状態）

## どのようにやっていくか / Approach, Detailed design

以下のように、上記3パターンを指定必須のpropsとする。

```ts
linkFollowType: 'all' | 'none' | 'firstPage';
```

`href`の生成でページ番号が必須なので、指定されたタイプとページ番号に基づき`rel="nofollow"`を付与するかの真偽値を返す関数を作成する。

```ts
function getLinkRelAttribute({ linkFollowType, pageNumber }) {
  switch (linkFollowType) {
    case 'all':
      return false;
    case 'none':
      return true;
    case 'firstPage':
      if (pageNumber === 1) {
        return false;
      } else {
        return true;
      }
  }
}
```

`getLinkRelAttribute`の戻り値が`true`の場合は`rel="nofollow"`を付与し、`false`の場合はrel属性を付与しない。

## 他の手段 / Alternative approach

より自由度を高めるなら、ページ遷移するリンクごとに`rel="nofollow"`を指定できるようにする。

### 方法1. リンクコンポーネントを切り出し、それに対してrelの指定をする

▽ Paginationコンポーネント側
```ts
export const usePaginationContext = () => {
  return React.useContext(PaginationContext);
};

const Container = ({ total, current, children }) => {
  return (
    <PaginationContext.Provider value={{ total, current }}>
      {children}
    </PaginationContext.Provider>
  )
}

export const Pagination = {
  Container,
  NumberLink,
  ArrowLink
};
```

▽ 利用イメージ
```ts
const List = () => {
  const { total, current } = usePaginationContext();

  return (
    <Pagination.Container>
      <Pagination.ArrowLink type="prev" current={current} total={total}  />
      {total.map((pageNumber) => {
          <Pagination.NumberLink current={current} pageNumber={pageNumber} rel="nofollow" />
      })}
     <Pagination.ArrowLink type="next" current={current} total={total} rel="nofollow"  />
    </Pagination.Container>
  )
}
```

- メリット
  - 利用側の実装に委ねられるので、仕様変更する場合でもSpindle側の修正が不要になる
- デメリット
  - 現在の実装から大きく変わる
  - `rel="nofollow"`のリンク設計に関して認知負荷が高まる
  - 利用側のテストコードなどで動作担保する必要があり、利用毎に実装コストがかかる（※ 利用側でパターン別のコンポーネントを作るのは良さそう）

### 方法2. totalページ数と同じ長さの配列を用意し、ページ番号ごとのrelに関する情報を格納する

▽ Paginationコンポーネント側
```ts
interface Props {
  ...,
  relList: boolean[];
}

const Pagination = ({ ..., relList }) => {
  return (
    ...
    displayItem.map((pageNumber) => {
      const hasRelAttribute = relList[pageNumber];

      return (
        <a rel={hasRelAttribute ? 'nofollow' : undefined}>
        ...
        </a>
      )
    })
    {showPrevNext && (
      <li>
       {/* PaginationItem内でhasRelAttributeの判定を行う */}
        <PaginationItem
          type="next"
          current={current}
          linkFollowType={linkFollowType}
          relList={relList}
          total={total}
          onClick={handleClick}
          createUrl={createUrl}
        />
      </li>
    )}
  )
}
```

▽ 利用イメージ

```ts
const List = () => {
  const relList = [false, false, true, ..., false];

  return (
    <Pagination
      createUrl={(page) =>
        getPageUrl(PageType.VideoList, { amebaId, page })
      }
      current={pageNumber}
      relList={relList}
      total={totalPage}
    />
  )
}
```

- メリット
  - 利用側の実装に委ねられるので、仕様変更する場合でもSpindle側の修正が不要になる
  - 現在の実装からあまり大きくは変わらなそう
- デメリット
  - `relList`作成周りのコードが汚くなりそう
  - `rel="nofollow"`のリンク設計に関して認知負荷が高まる
  - 利用側のテストコードなどで動作担保する必要があり、利用毎に実装コストがかかる（※ 利用側でパターン別のコンポーネントを作るのは良さそう）

## 想定される問題 / Drawback, Risk

今回の設計方針に関して想定される問題は

- パターンが増えた場合に都度追加修正が必要になる
- デフォルト値を用意していないとはいえ、SEO考慮がされていないタイプが勝手に指定される可能性

がありそう。

## 関連リンク / Related link

特になし。

**Comment by herablog** [comment]
@yasuda-shin Design Doc移行時こりも含めたいですね〜のメモ
