### ISSUE TITLE
color/theme-darkのHighlight.YellowのPrimitiveカラーが間違っている

### ISSUE THREAD

**Issue by dazy1030** [openameba/spindle#874]
https://github.com/openameba/spindle/blob/25fdd540d03dc32bdd6ebadb42915c68a97769c5/packages/spindle-tokens/tokens/color/theme-dark.json#L164

おそらくYellow 100ではなくYellow 30 alphaが正しい。

**Comment by herablog** [comment]
ありがとうございます、Figmaの設定違ってるっぽいので確認します。

**Comment by herablog** [comment]
確認取れましたので、#883 で修正します。
